project_id = "ojoamgdxcukezocugyeg"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://127.0.0.1:54324"
jwt_expiry = 3600

[auth.email]
enabled = true
double_confirm_changes = true
enable_signup = true

[db]
enabled = true
port = 54322
major_version = 15

[realtime]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"

[studio]
enabled = true
port = 54323

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true