// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojoamgdxcukezocugyeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qb2FtZ2R4Y3VrZXpvY3VneWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5OTA4NTcsImV4cCI6MjA3MTU2Njg1N30.udb6WmpYKNPif51aXlCpFDfOBJ7ShvAu14qAe7fZm0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});